import Head from "next/head"
import Start from "../components/firstpage/Start"
import Advices from "../components/firstpage/Adices"
// import { GetServerSideProps } from "next"

export default function Home() {
  return (
    <>
      <Head>
        <title>MyFitness</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://use.use.fontawesome.com/releases/v5.0.8/css/all.css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Start/>
        <Advices/>
      </div>
    </>
  )
}

// export const getServerSideProps: GetServerSideProps = async () => {
//   const res = await fetch("https://dummyjson.com/products")
//   const { products }: getAllData = await res.json()
//   console.log(products)
//   return {
//     props: {
//       products: products,
//     },
//   }
// }
