export const foodList = [
  {
    name: 'Banana (1 medium)',
    calories: 105,
    carbs: 27,
    fat: 0.4,
    protein: 1.3,
    sodium: 1,
    sugar: 14,
  },
  {
    name: 'Apple (1 medium)',
    calories: 95,
    carbs: 25,
    fat: 0.3,
    protein: 0.5,
    sodium: 2,
    sugar: 19,
  },
  {
    name: 'Chicken Breast (Cooked, Skinless, Boneless - 1 piece, 3 oz)',
    calories: 165,
    carbs: 0,
    fat: 3.6,
    protein: 31,
    sodium: 74,
    sugar: 0,
  },
  {
    name: 'Salmon (Cooked - 1 fillet, 3 oz)',
    calories: 175,
    carbs: 0,
    fat: 10,
    protein: 20,
    sodium: 50,
    sugar: 0,
  },
  {
    name: 'Broccoli (1 cup, chopped)',
    calories: 55,
    carbs: 11,
    fat: 0.6,
    protein: 3.7,
    sodium: 33,
    sugar: 1.7,
  },
  {
    name: 'Pasta (Cooked, Plain - 1 cup, cooked)',
    calories: 200,
    carbs: 41,
    fat: 1.3,
    protein: 7,
    sodium: 2,
    sugar: 0.8,
  },
  {
    name: 'Rice (Cooked, White - 1 cup, cooked)',
    calories: 205,
    carbs: 45,
    fat: 0.4,
    protein: 4.2,
    sodium: 0,
    sugar: 0.1,
  },
  {
    name: 'Egg (1 large)',
    calories: 68,
    carbs: 0.6,
    fat: 5,
    protein: 6,
    sodium: 63,
    sugar: 0.6,
  },
  {
    name: 'Spinach (1 cup, cooked)',
    calories: 41,
    carbs: 7,
    fat: 1,
    protein: 5,
    sodium: 583,
    sugar: 0.5,
  },
  {
    name: 'Milk (2% Fat - 1 cup)',
    calories: 122,
    carbs: 11,
    fat: 5,
    protein: 8,
    sodium: 121,
    sugar: 12,
  },
  // Add more food items here
  {
    name: 'Grilled Cheese Sandwich (1 sandwich)',
    calories: 400,
    carbs: 32,
    fat: 22,
    protein: 17,
    sodium: 780,
    sugar: 3,
  },
  {
    name: 'Orange Juice (1 cup)',
    calories: 120,
    carbs: 26,
    fat: 0.5,
    protein: 2,
    sodium: 0,
    sugar: 21,
  },
  {
    name: 'Pizza Slice (Pepperoni - 1 slice)',
    calories: 285,
    carbs: 36,
    fat: 11,
    protein: 12,
    sodium: 640,
    sugar: 3,
  },
  {
    name: 'Scrambled Eggs (2 large eggs)',
    calories: 140,
    carbs: 2,
    fat: 10,
    protein: 12,
    sodium: 340,
    sugar: 1,
  },
  {
    name: 'Boiled Eggs (2 large eggs)',
    calories: 154,
    carbs: 1.1,
    fat: 10.6,
    protein: 12.6,
    sodium: 124,
    sugar: 0.6,
  },
  {
    name: 'Egg Salad Sandwich (1 sandwich)',
    calories: 320,
    carbs: 22,
    fat: 20,
    protein: 15,
    sodium: 580,
    sugar: 3,
  },
  {
    name: 'Deviled Eggs (2 halves)',
    calories: 62,
    carbs: 0.6,
    fat: 4.8,
    protein: 3.3,
    sodium: 122,
    sugar: 0.2,
  },
  {
    name: 'Omelette with Cheese and Vegetables (1 serving)',
    calories: 320,
    carbs: 4,
    fat: 24,
    protein: 21,
    sodium: 680,
    sugar: 2,
  },
  {
    name: 'Egg McMuffin (1 sandwich)',
    calories: 300,
    carbs: 30,
    fat: 12,
    protein: 17,
    sodium: 730,
    sugar: 2,
  },
  {
    name: 'Egg Fried Rice (1 cup)',
    calories: 270,
    carbs: 39,
    fat: 8,
    protein: 10,
    sodium: 680,
    sugar: 1,
  },
  {
    name: 'Egg Drop Soup (1 cup)',
    calories: 68,
    carbs: 8,
    fat: 3,
    protein: 3,
    sodium: 760,
    sugar: 1,
  },
  {
    name: 'Egg Noodles (Cooked, 1 cup)',
    calories: 221,
    carbs: 40,
    fat: 3,
    protein: 8,
    sodium: 7,
    sugar: 1,
  },
  {
    name: 'Eggnog (1 cup)',
    calories: 343,
    carbs: 49,
    fat: 14,
    protein: 9,
    sodium: 95,
    sugar: 47,
  },
  {
    name: 'Eggplant Parmesan (1 serving)',
    calories: 356,
    carbs: 20,
    fat: 26,
    protein: 15,
    sodium: 880,
    sugar: 8,
  },
  {
    name: 'Egg Salad (1 cup)',
    calories: 357,
    carbs: 7,
    fat: 29,
    protein: 15,
    sodium: 633,
    sugar: 3,
  },
  {
    name: 'Eggs Benedict (1 serving)',
    calories: 541,
    carbs: 20,
    fat: 45,
    protein: 17,
    sodium: 920,
    sugar: 2,
  },
  {
    name: 'Egg Roll (1 roll)',
    calories: 200,
    carbs: 20,
    fat: 10,
    protein: 8,
    sodium: 400,
    sugar: 1,
  },
  {
    name: 'Eggplant Stir-Fry (1 serving)',
    calories: 198,
    carbs: 11,
    fat: 15,
    protein: 5,
    sodium: 433,
    sugar: 6,
  },
  {
    name: 'Egg Curry (1 serving)',
    calories: 262,
    carbs: 10,
    fat: 19,
    protein: 12,
    sodium: 680,
    sugar: 4,
  },
  {
    name: 'Egg Foo Young (1 patty)',
    calories: 90,
    carbs: 1,
    fat: 6,
    protein: 7,
    sodium: 260,
    sugar: 1,
  },
  {
    name: 'Eggplant Parmesan Sandwich (1 sandwich)',
    calories: 480,
    carbs: 52,
    fat: 21,
    protein: 21,
    sodium: 1160,
    sugar: 8,
  },
  {
    name: 'Eggplant Lasagna (1 serving)',
    calories: 320,
    carbs: 29,
    fat: 16,
    protein: 17,
    sodium: 540,
    sugar: 9,
  },
  {
    name: 'Eggplant Rollatini (1 serving)',
    calories: 300,
    carbs: 21,
    fat: 20,
    protein: 14,
    sodium: 780,
    sugar: 8,
  },
  {
    name: 'Egg Custard (1 serving)',
    calories: 175,
    carbs: 18,
    fat: 10,
    protein: 5,
    sodium: 83,
    sugar: 15,
  },
  {
    name: 'Eggless Chocolate Cake (1 slice)',
    calories: 210,
    carbs: 35,
    fat: 7,
    protein: 2,
    sodium: 170,
    sugar: 22,
  },
  {
    name: 'Eggplant Pizza (1 slice)',
    calories: 140,
    carbs: 14,
    fat: 7,
    protein: 7,
    sodium: 320,
    sugar: 2,
  },
  {
    name: 'Eggplant Frittata (1 slice)',
    calories: 120,
    carbs: 9,
    fat: 8,
    protein: 3,
    sodium: 320,
    sugar: 2,
  },
  {
    name: 'Egg Drop Noodle Soup (1 serving)',
    calories: 240,
    carbs: 45,
    fat: 4,
    protein: 7,
    sodium: 680,
    sugar: 3,
  },
  {
    name: 'Egg Nog Ice Cream (1 scoop)',
    calories: 180,
    carbs: 18,
    fat: 10,
    protein: 3,
    sodium: 45,
    sugar: 15,
  },
  {
    name: 'Egg Salad Wrap (1 wrap)',
    calories: 350,
    carbs: 34,
    fat: 17,
    protein: 14,
    sodium: 680,
    sugar: 3,
  },
  {
    name: 'Egg Drop Ramen Soup (1 serving)',
    calories: 340,
    carbs: 56,
    fat: 7,
    protein: 9,
    sodium: 960,
    sugar: 4,
  },
  {
    name: 'Eggplant and Mozzarella Panini (1 sandwich)',
    calories: 430,
    carbs: 45,
    fat: 18,
    protein: 21,
    sodium: 1120,
    sugar: 8,
  },
  {
    name: 'Eggplant Frittata (1 slice)',
    calories: 120,
    carbs: 9,
    fat: 8,
    protein: 3,
    sodium: 320,
    sugar: 2,
  },
  {
    name: 'Egg Drop Noodle Soup (1 serving)',
    calories: 240,
    carbs: 45,
    fat: 4,
    protein: 7,
    sodium: 680,
    sugar: 3,
  },
  {
    name: 'Egg Nog Ice Cream (1 scoop)',
    calories: 180,
    carbs: 18,
    fat: 10,
    protein: 3,
    sodium: 45,
    sugar: 15,
  },
  {
    name: 'Egg Salad Wrap (1 wrap)',
    calories: 350,
    carbs: 34,
    fat: 17,
    protein: 14,
    sodium: 680,
    sugar: 3,
  },
  {
    name: 'Egg Drop Ramen Soup (1 serving)',
    calories: 340,
    carbs: 56,
    fat: 7,
    protein: 9,
    sodium: 960,
    sugar: 4,
  },
  {
    name: 'Eggplant and Mozzarella Panini (1 sandwich)',
    calories: 430,
    carbs: 45,
    fat: 18,
    protein: 21,
    sodium: 1120,
    sugar: 8,
  },
  {
    name: 'Grilled Chicken Breast (Boneless, Skinless - 3 oz)',
    calories: 128,
    carbs: 0,
    fat: 3,
    protein: 26,
    sodium: 74,
    sugar: 0,
  },
  {
    name: 'Beef Steak (Cooked, Lean - 3 oz)',
    calories: 180,
    carbs: 0,
    fat: 8,
    protein: 26,
    sodium: 51,
    sugar: 0,
  },
  {
    name: 'Pork Chop (Cooked, Boneless - 3 oz)',
    calories: 153,
    carbs: 0,
    fat: 6,
    protein: 23,
    sodium: 42,
    sugar: 0,
  },
  {
    name: 'Salmon Fillet (Cooked - 3 oz)',
    calories: 155,
    carbs: 0,
    fat: 7,
    protein: 22,
    sodium: 48,
    sugar: 0,
  },
  {
    name: 'Ground Beef (Cooked, Lean - 3 oz)',
    calories: 180,
    carbs: 0,
    fat: 10,
    protein: 20,
    sodium: 56,
    sugar: 0,
  },
  {
    name: 'Turkey Breast (Cooked, Skinless - 3 oz)',
    calories: 135,
    carbs: 0,
    fat: 1,
    protein: 30,
    sodium: 50,
    sugar: 0,
  },
  {
    name: 'Lamb Chop (Cooked, Lean - 3 oz)',
    calories: 142,
    carbs: 0,
    fat: 6,
    protein: 21,
    sodium: 52,
    sugar: 0,
  },
  {
    name: 'Bison Burger (Cooked, Lean - 3 oz patty)',
    calories: 152,
    carbs: 0,
    fat: 7,
    protein: 21,
    sodium: 68,
    sugar: 0,
  },
  {
    name: 'Chicken Alfredo (1 serving)',
    calories: 490,
    carbs: 45,
    fat: 23,
    protein: 24,
    sodium: 1050,
    sugar: 2,
  },
  {
    name: 'Grilled Salmon Salad (1 salad)',
    calories: 300,
    carbs: 16,
    fat: 18,
    protein: 20,
    sodium: 650,
    sugar: 7,
  },
  {
    name: 'Pork Tenderloin (Cooked - 3 oz)',
    calories: 143,
    carbs: 0,
    fat: 3,
    protein: 26,
    sodium: 49,
    sugar: 0,
  },
  {
    name: 'BBQ Ribs (1 serving)',
    calories: 300,
    carbs: 20,
    fat: 20,
    protein: 15,
    sodium: 680,
    sugar: 10,
  },
  {
    name: 'Turkey Bacon (2 slices)',
    calories: 70,
    carbs: 0,
    fat: 4,
    protein: 6,
    sodium: 350,
    sugar: 0,
  },
  {
    name: 'Lamb Gyro (1 serving)',
    calories: 600,
    carbs: 50,
    fat: 36,
    protein: 22,
    sodium: 1080,
    sugar: 4,
  },
  {
    name: 'Beef Stroganoff (1 serving)',
    calories: 450,
    carbs: 35,
    fat: 27,
    protein: 18,
    sodium: 820,
    sugar: 4,
  },
  {
    name: 'Venison Steak (Cooked - 3 oz)',
    calories: 110,
    carbs: 0,
    fat: 1,
    protein: 24,
    sodium: 40,
    sugar: 0,
  },
  {
    name: 'Roast Duck (Cooked - 3 oz)',
    calories: 135,
    carbs: 0,
    fat: 11,
    protein: 8,
    sodium: 60,
    sugar: 0,
  },
  {
    name: 'Sausage Link (Cooked - 1 link)',
    calories: 85,
    carbs: 0,
    fat: 7,
    protein: 4,
    sodium: 270,
    sugar: 0,
  },
  {
    name: 'Veal Cutlet (Cooked - 3 oz)',
    calories: 160,
    carbs: 0,
    fat: 7,
    protein: 24,
    sodium: 50,
    sugar: 0,
  },
  {
    name: 'Pepperoni Pizza (1 slice)',
    calories: 298,
    carbs: 26,
    fat: 15,
    protein: 13,
    sodium: 570,
    sugar: 2,
  },
  {
    name: 'Beef and Broccoli Stir-Fry (1 serving)',
    calories: 280,
    carbs: 12,
    fat: 15,
    protein: 23,
    sodium: 800,
    sugar: 3,
  },
  {
    name: 'Grilled Tuna Steak (3 oz)',
    calories: 120,
    carbs: 0,
    fat: 1,
    protein: 25,
    sodium: 40,
    sugar: 0,
  },
  {
    name: 'Italian Meatball Sub (1 sandwich)',
    calories: 560,
    carbs: 50,
    fat: 27,
    protein: 31,
    sodium: 1450,
    sugar: 10,
  },
  {
    name: 'Chicken Quesadilla (1 serving)',
    calories: 320,
    carbs: 24,
    fat: 16,
    protein: 19,
    sodium: 690,
    sugar: 1,
  },
  {
    name: 'Pulled Pork Sandwich (1 sandwich)',
    calories: 370,
    carbs: 37,
    fat: 14,
    protein: 23,
    sodium: 720,
    sugar: 11,
  },
  {
    name: 'Bacon and Egg Breakfast Burrito (1 burrito)',
    calories: 350,
    carbs: 31,
    fat: 20,
    protein: 14,
    sodium: 720,
    sugar: 3,
  },
  {
    name: 'Sausage and Peppers (1 serving)',
    calories: 280,
    carbs: 5,
    fat: 21,
    protein: 16,
    sodium: 700,
    sugar: 3,
  },
  {
    name: 'Grilled Lamb Kebab (1 skewer)',
    calories: 230,
    carbs: 0,
    fat: 15,
    protein: 23,
    sodium: 370,
    sugar: 0,
  },
  {
    name: 'Corned Beef Hash (1 serving)',
    calories: 380,
    carbs: 22,
    fat: 29,
    protein: 8,
    sodium: 1020,
    sugar: 1,
  },
  {
    name: 'Teriyaki Beef Stir-Fry (1 serving)',
    calories: 320,
    carbs: 18,
    fat: 12,
    protein: 32,
    sodium: 920,
    sugar: 13,
  },
  {
    name: 'Chicken Bacon Ranch Wrap (1 wrap)',
    calories: 420,
    carbs: 35,
    fat: 24,
    protein: 19,
    sodium: 980,
    sugar: 3,
  },
  {
    name: 'Honey Glazed Ham (3 oz)',
    calories: 120,
    carbs: 10,
    fat: 4,
    protein: 10,
    sodium: 620,
    sugar: 9,
  },
  {
    name: 'Almonds (1 oz)',
    calories: 160,
    carbs: 6,
    fat: 14,
    protein: 6,
    sodium: 0,
    sugar: 1,
  },
  {
    name: 'Walnuts (1 oz)',
    calories: 185,
    carbs: 4,
    fat: 18,
    protein: 4,
    sodium: 0,
    sugar: 1,
  },
  {
    name: 'Cashews (1 oz)',
    calories: 155,
    carbs: 9,
    fat: 12,
    protein: 5,
    sodium: 3,
    sugar: 1,
  },
  {
    name: 'Pistachios (1 oz)',
    calories: 160,
    carbs: 8,
    fat: 14,
    protein: 6,
    sodium: 0,
    sugar: 2,
  },
  {
    name: 'Dried Apricots (1 oz)',
    calories: 67,
    carbs: 18,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 12,
  },
  {
    name: 'Raisins (1 oz)',
    calories: 85,
    carbs: 22,
    fat: 0,
    protein: 1,
    sodium: 5,
    sugar: 16,
  },
  {
    name: 'Dried Cranberries (1 oz)',
    calories: 95,
    carbs: 25,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 20,
  },
  {
    name: 'Dried Figs (1 oz)',
    calories: 47,
    carbs: 12,
    fat: 0,
    protein: 1,
    sodium: 1,
    sugar: 9,
  },
  {
    name: 'Dates (1 oz)',
    calories: 23,
    carbs: 6,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 5,
  },
  {
    name: 'Prunes (1 oz)',
    calories: 20,
    carbs: 5,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 3,
  },
  {
    name: 'Dried Blueberries (1 oz)',
    calories: 84,
    carbs: 22,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 16,
  },
  {
    name: 'Dried Mango (1 oz)',
    calories: 107,
    carbs: 28,
    fat: 0,
    protein: 0,
    sodium: 3,
    sugar: 18,
  },
  {
    name: 'Dried Pineapple (1 oz)',
    calories: 82,
    carbs: 22,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 16,
  },
  {
    name: 'Dried Papaya (1 oz)',
    calories: 59,
    carbs: 15,
    fat: 0,
    protein: 0,
    sodium: 2,
    sugar: 9,
  },
  {
    name: 'Dried Kiwi (1 oz)',
    calories: 81,
    carbs: 21,
    fat: 0,
    protein: 1,
    sodium: 1,
    sugar: 13,
  },
  {
    name: 'Dried Goji Berries (1 oz)',
    calories: 98,
    carbs: 21,
    fat: 0,
    protein: 4,
    sodium: 75,
    sugar: 17,
  },
  {
    name: 'Dried Cranberries (Sweetened - 1 oz)',
    calories: 95,
    carbs: 25,
    fat: 0,
    protein: 0,
    sodium: 2,
    sugar: 20,
  },
  {
    name: 'Dried Cherries (1 oz)',
    calories: 95,
    carbs: 25,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 20,
  },
  {
    name: 'Dried Apples (1 oz)',
    calories: 95,
    carbs: 25,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 19,
  },
  {
    name: 'Dried Pears (1 oz)',
    calories: 90,
    carbs: 23,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 16,
  },
  {
    name: 'Dried Plums (1 oz)',
    calories: 63,
    carbs: 16,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 9,
  },
  {
    name: 'Dried Guava (1 oz)',
    calories: 98,
    carbs: 25,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 15,
  },
  {
    name: 'Dried Persimmons (1 oz)',
    calories: 81,
    carbs: 21,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 17,
  },
  {
    name: 'Dried Mulberries (1 oz)',
    calories: 88,
    carbs: 22,
    fat: 1,
    protein: 2,
    sodium: 12,
    sugar: 14,
  },
  {
    name: 'Dried Blackberries (1 oz)',
    calories: 74,
    carbs: 18,
    fat: 0,
    protein: 2,
    sodium: 1,
    sugar: 10,
  },
  {
    name: 'Dried Lychee (1 oz)',
    calories: 92,
    carbs: 24,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 19,
  },
  {
    name: 'Dried Raspberry (1 oz)',
    calories: 79,
    carbs: 20,
    fat: 1,
    protein: 1,
    sodium: 2,
    sugar: 14,
  },
  {
    name: 'Dried Watermelon (1 oz)',
    calories: 92,
    carbs: 23,
    fat: 0,
    protein: 1,
    sodium: 1,
    sugar: 21,
  },
  {
    name: 'Dried Passion Fruit (1 oz)',
    calories: 104,
    carbs: 27,
    fat: 0,
    protein: 1,
    sodium: 3,
    sugar: 20,
  },
  {
    name: 'Dried Dragon Fruit (1 oz)',
    calories: 100,
    carbs: 26,
    fat: 0,
    protein: 1,
    sodium: 10,
    sugar: 17,
  },
  {
    name: 'Dried Persimmons (1 oz)',
    calories: 81,
    carbs: 21,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 17,
  },
  {
    name: 'Dried Mulberries (1 oz)',
    calories: 88,
    carbs: 22,
    fat: 1,
    protein: 2,
    sodium: 12,
    sugar: 14,
  },
  {
    name: 'Cooked White Rice (1 cup)',
    calories: 205,
    carbs: 45,
    fat: 0,
    protein: 4,
    sodium: 1,
    sugar: 0,
  },
  {
    name: 'Cooked Brown Rice (1 cup)',
    calories: 215,
    carbs: 45,
    fat: 2,
    protein: 5,
    sodium: 2,
    sugar: 0,
  },
  {
    name: 'Cooked Quinoa (1 cup)',
    calories: 222,
    carbs: 39,
    fat: 4,
    protein: 8,
    sodium: 7,
    sugar: 1,
  },
  {
    name: 'Cooked Pasta (1 cup)',
    calories: 200,
    carbs: 40,
    fat: 1,
    protein: 7,
    sodium: 1,
    sugar: 2,
  },
  {
    name: 'Cooked Couscous (1 cup)',
    calories: 176,
    carbs: 36,
    fat: 0,
    protein: 6,
    sodium: 7,
    sugar: 0,
  },
  {
    name: 'Cooked Bulgur (1 cup)',
    calories: 151,
    carbs: 34,
    fat: 0,
    protein: 5,
    sodium: 3,
    sugar: 0,
  },
  {
    name: 'Cooked Oatmeal (1 cup)',
    calories: 147,
    carbs: 25,
    fat: 3,
    protein: 6,
    sodium: 2,
    sugar: 0,
  },
  {
    name: 'Cooked Barley (1 cup)',
    calories: 193,
    carbs: 44,
    fat: 1,
    protein: 3,
    sodium: 2,
    sugar: 0,
  },
  {
    name: 'Cooked Lentils (1 cup)',
    calories: 230,
    carbs: 40,
    fat: 1,
    protein: 18,
    sodium: 4,
    sugar: 2,
  },
  {
    name: 'Cooked Chickpeas (1 cup)',
    calories: 269,
    carbs: 45,
    fat: 5,
    protein: 15,
    sodium: 15,
    sugar: 8,
  },
  {
    name: 'Cooked Black Beans (1 cup)',
    calories: 227,
    carbs: 41,
    fat: 0,
    protein: 15,
    sodium: 1,
    sugar: 1,
  },
  {
    name: 'Cooked Salmon (3 oz)',
    calories: 180,
    carbs: 0,
    fat: 9,
    protein: 23,
    sodium: 48,
    sugar: 0,
  },
  {
    name: 'Cooked Chicken Breast (3 oz)',
    calories: 128,
    carbs: 0,
    fat: 2,
    protein: 26,
    sodium: 42,
    sugar: 0,
  },
  {
    name: 'Cooked Tofu (3 oz)',
    calories: 70,
    carbs: 2,
    fat: 4,
    protein: 8,
    sodium: 3,
    sugar: 0,
  },
  {
    name: 'Cooked Shrimp (3 oz)',
    calories: 84,
    carbs: 0,
    fat: 1,
    protein: 18,
    sodium: 180,
    sugar: 0,
  },
  {
    name: 'Cooked Spinach (1 cup)',
    calories: 41,
    carbs: 7,
    fat: 1,
    protein: 5,
    sodium: 136,
    sugar: 0,
  },
  {
    name: 'Spinach (1 cup, cooked)',
    calories: 41,
    carbs: 7,
    fat: 1,
    protein: 5,
    sodium: 136,
    sugar: 0,
  },
  {
    name: 'Kale (1 cup, cooked)',
    calories: 36,
    carbs: 7,
    fat: 1,
    protein: 2,
    sodium: 23,
    sugar: 0,
  },
  {
    name: 'Broccoli (1 cup, cooked)',
    calories: 55,
    carbs: 11,
    fat: 1,
    protein: 3,
    sodium: 61,
    sugar: 2,
  },
  {
    name: 'Spinach (1 cup, raw)',
    calories: 7,
    carbs: 1,
    fat: 0,
    protein: 1,
    sodium: 24,
    sugar: 0,
  },
  {
    name: 'Kale (1 cup, raw)',
    calories: 8,
    carbs: 2,
    fat: 0,
    protein: 1,
    sodium: 9,
    sugar: 0,
  },
  {
    name: 'Broccoli (1 cup, raw)',
    calories: 31,
    carbs: 6,
    fat: 0,
    protein: 3,
    sodium: 30,
    sugar: 2,
  },
  {
    name: 'Green Beans (1 cup, cooked)',
    calories: 31,
    carbs: 7,
    fat: 0,
    protein: 2,
    sodium: 6,
    sugar: 3,
  },
  {
    name: 'Asparagus (1 cup, cooked)',
    calories: 40,
    carbs: 8,
    fat: 0,
    protein: 4,
    sodium: 4,
    sugar: 2,
  },
  {
    name: 'Green Peas (1 cup, cooked)',
    calories: 62,
    carbs: 12,
    fat: 0,
    protein: 4,
    sodium: 2,
    sugar: 4,
  },
  {
    name: 'Zucchini (1 cup, cooked)',
    calories: 17,
    carbs: 3,
    fat: 0,
    protein: 1,
    sodium: 8,
    sugar: 2,
  },
  {
    name: 'Collard Greens (1 cup, cooked)',
    calories: 49,
    carbs: 11,
    fat: 0,
    protein: 4,
    sodium: 9,
    sugar: 1,
  },
  {
    name: 'Swiss Chard (1 cup, cooked)',
    calories: 35,
    carbs: 7,
    fat: 1,
    protein: 3,
    sodium: 313,
    sugar: 1,
  },
  {
    name: 'Bok Choy (1 cup, cooked)',
    calories: 20,
    carbs: 4,
    fat: 0,
    protein: 2,
    sodium: 171,
    sugar: 1,
  },
  {
    name: 'Cucumber (1 cup, sliced)',
    calories: 16,
    carbs: 4,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 1,
  },
  {
    name: 'Green Bell Pepper (1 cup, sliced)',
    calories: 18,
    carbs: 4,
    fat: 0,
    protein: 1,
    sodium: 3,
    sugar: 2,
  },
  {
    name: 'Brussels Sprouts (1 cup, cooked)',
    calories: 56,
    carbs: 12,
    fat: 1,
    protein: 3,
    sodium: 23,
    sugar: 2,
  },
  {
    name: 'Artichoke (1 medium, cooked)',
    calories: 60,
    carbs: 14,
    fat: 0,
    protein: 3,
    sodium: 94,
    sugar: 1,
  },
  {
    name: 'Okra (1 cup, cooked)',
    calories: 31,
    carbs: 7,
    fat: 0,
    protein: 2,
    sodium: 8,
    sugar: 1,
  },
  {
    name: 'Cilantro (1 cup, chopped)',
    calories: 0,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 1,
    sugar: 0,
  },
  {
    name: 'Sage (1 tablespoon, ground)',
    calories: 6,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 1,
    sugar: 0,
  },
  {
    name: 'Thyme (1 tablespoon, dried)',
    calories: 3,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 1,
    sugar: 0,
  },
  {
    name: 'Dill (1 tablespoon, dried)',
    calories: 3,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 1,
    sugar: 0,
  },
  {
    name: 'Parsley (1 cup, chopped)',
    calories: 22,
    carbs: 5,
    fat: 0,
    protein: 2,
    sodium: 38,
    sugar: 1,
  },
  {
    name: 'Watercress (1 cup, chopped)',
    calories: 4,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 2,
    sugar: 0,
  },
  {
    name: 'Basil (1 cup, chopped)',
    calories: 2,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
  },
  {
    name: 'Mint (1 cup, chopped)',
    calories: 6,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 1,
    sugar: 0,
  },
  {
    name: 'Arugula (1 cup, raw)',
    calories: 5,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 4,
    sugar: 0,
  },
  {
    name: 'Chives (1 tablespoon, chopped)',
    calories: 0,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
  },
  {
    name: 'Coriander (1 tablespoon, dried)',
    calories: 5,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 1,
    sugar: 0,
  },
  {
    name: 'Parsley (1 tablespoon, dried)',
    calories: 5,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 1,
    sugar: 0,
  },
  {
    name: 'Cilantro (1 tablespoon, chopped)',
    calories: 0,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 1,
    sugar: 0,
  },
  {
    name: 'Tarragon (1 tablespoon, dried)',
    calories: 3,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
  },
  {
    name: 'Sorrel (1 cup, raw)',
    calories: 4,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 2,
    sugar: 0,
  },
  {
    name: 'Savoy Cabbage (1 cup, cooked)',
    calories: 44,
    carbs: 10,
    fat: 0,
    protein: 2,
    sodium: 17,
    sugar: 3,
  },
  {
    name: 'Chicory (1 cup, chopped)',
    calories: 5,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 4,
    sugar: 0,
  },
  {
    name: 'Endive (1 cup, chopped)',
    calories: 8,
    carbs: 2,
    fat: 0,
    protein: 0,
    sodium: 17,
    sugar: 0,
  },
  {
    name: 'Dandelion Greens (1 cup, raw)',
    calories: 25,
    carbs: 5,
    fat: 0,
    protein: 2,
    sodium: 76,
    sugar: 0,
  },
  {
    name: 'Mustard Greens (1 cup, cooked)',
    calories: 21,
    carbs: 3,
    fat: 0,
    protein: 3,
    sodium: 18,
    sugar: 0,
  },
  {
    name: 'Collard Greens (1 cup, raw)',
    calories: 11,
    carbs: 2,
    fat: 0,
    protein: 1,
    sodium: 12,
    sugar: 0,
  },
  {
    name: 'Bok Choy (1 cup, raw)',
    calories: 9,
    carbs: 2,
    fat: 0,
    protein: 1,
    sodium: 158,
    sugar: 1,
  },
  {
    name: 'Sorrel (1 cup, raw)',
    calories: 4,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 2,
    sugar: 0,
  },
  {
    name: 'Savoy Cabbage (1 cup, cooked)',
    calories: 44,
    carbs: 10,
    fat: 0,
    protein: 2,
    sodium: 17,
    sugar: 3,
  },
  {
    name: 'Chicory (1 cup, chopped)',
    calories: 5,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 4,
    sugar: 0,
  },
  {
    name: 'Endive (1 cup, chopped)',
    calories: 8,
    carbs: 2,
    fat: 0,
    protein: 0,
    sodium: 17,
    sugar: 0,
  },
  {
    name: 'Dandelion Greens (1 cup, raw)',
    calories: 25,
    carbs: 5,
    fat: 0,
    protein: 2,
    sodium: 76,
    sugar: 0,
  },
  {
    name: 'Mustard Greens (1 cup, cooked)',
    calories: 21,
    carbs: 3,
    fat: 0,
    protein: 3,
    sodium: 18,
    sugar: 0,
  },
  {
    name: 'Collard Greens (1 cup, raw)',
    calories: 11,
    carbs: 2,
    fat: 0,
    protein: 1,
    sodium: 12,
    sugar: 0,
  },
  {
    name: 'Bok Choy (1 cup, raw)',
    calories: 9,
    carbs: 2,
    fat: 0,
    protein: 1,
    sodium: 158,
    sugar: 1,
  },
  {
    name: 'Sorrel (1 cup, raw)',
    calories: 4,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 2,
    sugar: 0,
  },
  {
    name: 'Savoy Cabbage (1 cup, cooked)',
    calories: 44,
    carbs: 10,
    fat: 0,
    protein: 2,
    sodium: 17,
    sugar: 3,
  },
  {
    name: 'Chicory (1 cup, chopped)',
    calories: 5,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 4,
    sugar: 0,
  },
  {
    name: 'Endive (1 cup, chopped)',
    calories: 8,
    carbs: 2,
    fat: 0,
    protein: 0,
    sodium: 17,
    sugar: 0,
  },
  {
    name: 'Dandelion Greens (1 cup, raw)',
    calories: 25,
    carbs: 5,
    fat: 0,
    protein: 2,
    sodium: 76,
    sugar: 0,
  },
  {
    name: 'Mustard Greens (1 cup, cooked)',
    calories: 21,
    carbs: 3,
    fat: 0,
    protein: 3,
    sodium: 18,
    sugar: 0,
  },
  {
    name: 'Collard Greens (1 cup, raw)',
    calories: 11,
    carbs: 2,
    fat: 0,
    protein: 1,
    sodium: 12,
    sugar: 0,
  },
  {
    name: 'Bok Choy (1 cup, raw)',
    calories: 9,
    carbs: 2,
    fat: 0,
    protein: 1,
    sodium: 158,
    sugar: 1,
  },
  {
    name: 'Fennel (1 cup, sliced)',
    calories: 27,
    carbs: 6,
    fat: 0,
    protein: 1,
    sodium: 45,
    sugar: 3,
  },
  {
    name: 'Cabbage (1 cup, cooked)',
    calories: 33,
    carbs: 8,
    fat: 0,
    protein: 1,
    sodium: 19,
    sugar: 3,
  },
  {
    name: 'Chicory Root (1 cup, raw)',
    calories: 8,
    carbs: 2,
    fat: 0,
    protein: 0,
    sodium: 14,
    sugar: 0,
  },
  {
    name: 'Romaine Lettuce (1 cup, shredded)',
    calories: 8,
    carbs: 2,
    fat: 0,
    protein: 1,
    sodium: 7,
    sugar: 1,
  },
  {
    name: 'Green Onions (1 cup, chopped)',
    calories: 19,
    carbs: 4,
    fat: 0,
    protein: 1,
    sodium: 12,
    sugar: 2,
  },
  {
    name: 'Cress (1 cup, raw)',
    calories: 4,
    carbs: 1,
    fat: 0,
    protein: 0,
    sodium: 3,
    sugar: 0,
  },
  {
    name: 'Turnip Greens (1 cup, cooked)',
    calories: 18,
    carbs: 4,
    fat: 0,
    protein: 2,
    sodium: 10,
    sugar: 1,
  },
  {
    name: 'Water Spinach (1 cup, raw)',
    calories: 20,
    carbs: 5,
    fat: 0,
    protein: 2,
    sodium: 17,
    sugar: 0,
  },
  {
    name: 'Apple (1 medium)',
    calories: 95,
    carbs: 25,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 19,
  },
  {
    name: 'Banana (1 medium)',
    calories: 105,
    carbs: 27,
    fat: 0,
    protein: 1,
    sodium: 1,
    sugar: 14,
  },
  {
    name: 'Orange (1 medium)',
    calories: 62,
    carbs: 15,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 12,
  },
  {
    name: 'Grapes (1 cup, seedless)',
    calories: 104,
    carbs: 27,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 23,
  },
  {
    name: 'Strawberries (1 cup, sliced)',
    calories: 53,
    carbs: 13,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 8,
  },
  {
    name: 'Blueberries (1 cup)',
    calories: 84,
    carbs: 21,
    fat: 1,
    protein: 1,
    sodium: 1,
    sugar: 15,
  },
  {
    name: 'Pineapple (1 cup, chunks)',
    calories: 82,
    carbs: 22,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 16,
  },
  {
    name: 'Mango (1 cup, sliced)',
    calories: 150,
    carbs: 38,
    fat: 1,
    protein: 2,
    sodium: 3,
    sugar: 35,
  },
  {
    name: 'Apple (1 medium)',
    calories: 95,
    carbs: 25,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 19,
  },
  {
    name: 'Banana (1 medium)',
    calories: 105,
    carbs: 27,
    fat: 0,
    protein: 1,
    sodium: 1,
    sugar: 14,
  },
  {
    name: 'Orange (1 medium)',
    calories: 62,
    carbs: 15,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 12,
  },
  {
    name: 'Grapes (1 cup, seedless)',
    calories: 104,
    carbs: 27,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 23,
  },
  {
    name: 'Strawberries (1 cup, sliced)',
    calories: 53,
    carbs: 13,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 8,
  },
  {
    name: 'Blueberries (1 cup)',
    calories: 84,
    carbs: 21,
    fat: 1,
    protein: 1,
    sodium: 1,
    sugar: 15,
  },
  {
    name: 'Pineapple (1 cup, chunks)',
    calories: 82,
    carbs: 22,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 16,
  },
  {
    name: 'Mango (1 cup, sliced)',
    calories: 150,
    carbs: 38,
    fat: 1,
    protein: 2,
    sodium: 3,
    sugar: 35,
  },
  {
    name: 'Peach (1 medium)',
    calories: 59,
    carbs: 15,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 13,
  },
  {
    name: 'Pear (1 medium)',
    calories: 57,
    carbs: 15,
    fat: 0,
    protein: 1,
    sodium: 1,
    sugar: 10,
  },
  {
    name: 'Kiwi (1 medium)',
    calories: 61,
    carbs: 15,
    fat: 0,
    protein: 1,
    sodium: 3,
    sugar: 9,
  },
  {
    name: 'Apricot (1 medium)',
    calories: 17,
    carbs: 4,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 3,
  },
  {
    name: 'Cantaloupe (1 cup, diced)',
    calories: 54,
    carbs: 14,
    fat: 0,
    protein: 1,
    sodium: 28,
    sugar: 13,
  },
  {
    name: 'Pomegranate (1 cup, arils)',
    calories: 83,
    carbs: 19,
    fat: 1,
    protein: 2,
    sodium: 3,
    sugar: 14,
  },
  {
    name: 'Cherry (1 cup, pitted)',
    calories: 87,
    carbs: 22,
    fat: 0,
    protein: 1,
    sodium: 3,
    sugar: 18,
  },
  {
    name: 'Blackberry (1 cup)',
    calories: 62,
    carbs: 14,
    fat: 0,
    protein: 2,
    sodium: 1,
    sugar: 7,
  },
  {
    name: 'Raspberry (1 cup)',
    calories: 64,
    carbs: 15,
    fat: 1,
    protein: 1,
    sodium: 1,
    sugar: 5,
  },
  {
    name: 'Grapefruit (1/2 medium)',
    calories: 52,
    carbs: 13,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 8,
  },
  {
    name: 'Cranberries (1 cup, raw)',
    calories: 46,
    carbs: 12,
    fat: 0,
    protein: 0,
    sodium: 2,
    sugar: 4,
  },
  {
    name: 'Plum (1 medium)',
    calories: 46,
    carbs: 12,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 9,
  },
  {
    name: 'Guava (1 medium)',
    calories: 112,
    carbs: 24,
    fat: 1,
    protein: 4,
    sodium: 3,
    sugar: 9,
  },
  {
    name: 'Papaya (1 cup, cubes)',
    calories: 62,
    carbs: 16,
    fat: 0,
    protein: 1,
    sodium: 11,
    sugar: 11,
  },
  {
    name: 'Lychee (1 cup)',
    calories: 125,
    carbs: 32,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 29,
  },
  {
    name: 'Passion Fruit (1 fruit)',
    calories: 17,
    carbs: 4,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 4,
  },
  {
    name: 'Raspberry (1 cup)',
    calories: 64,
    carbs: 15,
    fat: 1,
    protein: 1,
    sodium: 1,
    sugar: 5,
  },
  {
    name: 'Grapefruit (1/2 medium)',
    calories: 52,
    carbs: 13,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 8,
  },
  {
    name: 'Cranberries (1 cup, raw)',
    calories: 46,
    carbs: 12,
    fat: 0,
    protein: 0,
    sodium: 2,
    sugar: 4,
  },
  {
    name: 'Plum (1 medium)',
    calories: 46,
    carbs: 12,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 9,
  },
  {
    name: 'Guava (1 medium)',
    calories: 112,
    carbs: 24,
    fat: 1,
    protein: 4,
    sodium: 3,
    sugar: 9,
  },
  {
    name: 'Papaya (1 cup, cubes)',
    calories: 62,
    carbs: 16,
    fat: 0,
    protein: 1,
    sodium: 11,
    sugar: 11,
  },
  {
    name: 'Lychee (1 cup)',
    calories: 125,
    carbs: 32,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 29,
  },
  {
    name: 'Passion Fruit (1 fruit)',
    calories: 17,
    carbs: 4,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 4,
  },
  {
    name: 'Mandarin Orange (1 medium)',
    calories: 47,
    carbs: 12,
    fat: 0,
    protein: 1,
    sodium: 1,
    sugar: 9,
  },
  {
    name: 'Nectarine (1 medium)',
    calories: 62,
    carbs: 15,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 11,
  },
  {
    name: 'Starfruit (1 medium)',
    calories: 28,
    carbs: 7,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 4,
  },
  {
    name: 'Dragon Fruit (1 cup, diced)',
    calories: 136,
    carbs: 29,
    fat: 0,
    protein: 4,
    sodium: 8,
    sugar: 8,
  },
  {
    name: 'Kiwi (1 medium)',
    calories: 61,
    carbs: 15,
    fat: 0,
    protein: 1,
    sodium: 3,
    sugar: 9,
  },
  {
    name: 'Clementine (1 medium)',
    calories: 35,
    carbs: 9,
    fat: 0,
    protein: 1,
    sodium: 0,
    sugar: 7,
  },
  {
    name: 'Currants (1 cup)',
    calories: 62,
    carbs: 15,
    fat: 0,
    protein: 1,
    sodium: 1,
    sugar: 9,
  },
  {
    name: 'Boysenberries (1 cup)',
    calories: 66,
    carbs: 16,
    fat: 0,
    protein: 2,
    sodium: 1,
    sugar: 7,
  },
  {
    name: 'Water (8 oz)',
    calories: 0,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
  },
  {
    name: 'Black Coffee (8 oz)',
    calories: 2,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 5,
    sugar: 0,
  },
  {
    name: 'Green Tea (8 oz)',
    calories: 2,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
  },
  {
    name: 'Milk (1 cup, whole)',
    calories: 149,
    carbs: 12,
    fat: 8,
    protein: 8,
    sodium: 98,
    sugar: 12,
  },
  {
    name: 'Orange Juice (8 oz)',
    calories: 112,
    carbs: 26,
    fat: 0,
    protein: 2,
    sodium: 2,
    sugar: 20,
  },
  {
    name: 'Coca-Cola (12 oz)',
    calories: 140,
    carbs: 39,
    fat: 0,
    protein: 0,
    sodium: 45,
    sugar: 39,
  },
  {
    name: 'Lemonade (8 oz)',
    calories: 99,
    carbs: 26,
    fat: 0,
    protein: 0,
    sodium: 10,
    sugar: 25,
  },
  {
    name: 'Iced Tea (8 oz, sweetened)',
    calories: 88,
    carbs: 24,
    fat: 0,
    protein: 0,
    sodium: 8,
    sugar: 24,
  },
  {
    name: 'Water (8 oz)',
    calories: 0,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
  },
  {
    name: 'Black Coffee (8 oz)',
    calories: 2,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 5,
    sugar: 0,
  },
  {
    name: 'Green Tea (8 oz)',
    calories: 2,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
  },
  {
    name: 'Milk (1 cup, whole)',
    calories: 149,
    carbs: 12,
    fat: 8,
    protein: 8,
    sodium: 98,
    sugar: 12,
  },
  {
    name: 'Orange Juice (8 oz)',
    calories: 112,
    carbs: 26,
    fat: 0,
    protein: 2,
    sodium: 2,
    sugar: 20,
  },
  {
    name: 'Coca-Cola (12 oz)',
    calories: 140,
    carbs: 39,
    fat: 0,
    protein: 0,
    sodium: 45,
    sugar: 39,
  },
  {
    name: 'Lemonade (8 oz)',
    calories: 99,
    carbs: 26,
    fat: 0,
    protein: 0,
    sodium: 10,
    sugar: 25,
  },
  {
    name: 'Iced Tea (8 oz, sweetened)',
    calories: 88,
    carbs: 24,
    fat: 0,
    protein: 0,
    sodium: 8,
    sugar: 24,
  },
  {
    name: 'Apple Juice (8 oz)',
    calories: 114,
    carbs: 28,
    fat: 0,
    protein: 0,
    sodium: 5,
    sugar: 24,
  },
  {
    name: 'Grape Juice (8 oz)',
    calories: 152,
    carbs: 38,
    fat: 0,
    protein: 1,
    sodium: 5,
    sugar: 36,
  },
  {
    name: 'Tomato Juice (8 oz)',
    calories: 41,
    carbs: 10,
    fat: 0,
    protein: 2,
    sodium: 654,
    sugar: 8,
  },
  {
    name: 'Pineapple Juice (8 oz)',
    calories: 132,
    carbs: 33,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 29,
  },
  {
    name: 'Iced Coffee (8 oz, sweetened)',
    calories: 130,
    carbs: 25,
    fat: 4,
    protein: 2,
    sodium: 30,
    sugar: 20,
  },
  {
    name: 'Limeade (8 oz)',
    calories: 98,
    carbs: 25,
    fat: 0,
    protein: 0,
    sodium: 5,
    sugar: 23,
  },
  {
    name: 'Mango Lassi (8 oz)',
    calories: 185,
    carbs: 31,
    fat: 5,
    protein: 5,
    sodium: 56,
    sugar: 26,
  },
  {
    name: 'Coconut Water (8 oz)',
    calories: 46,
    carbs: 9,
    fat: 0,
    protein: 2,
    sodium: 252,
    sugar: 6,
  },
  {
    name: 'Hot Chocolate (8 oz)',
    calories: 192,
    carbs: 26,
    fat: 8,
    protein: 5,
    sodium: 181,
    sugar: 23,
  },
  {
    name: 'Iced Latte (8 oz, sweetened)',
    calories: 120,
    carbs: 21,
    fat: 3,
    protein: 3,
    sodium: 60,
    sugar: 21,
  },
  {
    name: 'Ginger Tea (8 oz)',
    calories: 2,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 1,
    sugar: 0,
  },
  {
    name: 'Hot Tea (8 oz)',
    calories: 2,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 2,
    sugar: 0,
  },
  {
    name: 'Lemon Water (8 oz)',
    calories: 1,
    carbs: 4,
    fat: 0,
    protein: 0,
    sodium: 1,
    sugar: 1,
  },
  {
    name: 'Grapefruit Juice (8 oz)',
    calories: 96,
    carbs: 23,
    fat: 0,
    protein: 1,
    sodium: 2,
    sugar: 19,
  },
  {
    name: 'Pineapple Coconut Smoothie (8 oz)',
    calories: 138,
    carbs: 32,
    fat: 0,
    protein: 2,
    sodium: 10,
    sugar: 28,
  },
  {
    name: 'Iced Green Tea (8 oz, sweetened)',
    calories: 88,
    carbs: 24,
    fat: 0,
    protein: 0,
    sodium: 8,
    sugar: 24,
  },
  {
    name: 'Cranberry Juice (8 oz)',
    calories: 116,
    carbs: 30,
    fat: 0,
    protein: 0,
    sodium: 2,
    sugar: 28,
  },
  {
    name: 'Peach Iced Tea (8 oz, sweetened)',
    calories: 88,
    carbs: 22,
    fat: 0,
    protein: 0,
    sodium: 5,
    sugar: 22,
  },
  {
    name: 'Pomegranate Juice (8 oz)',
    calories: 134,
    carbs: 32,
    fat: 0,
    protein: 1,
    sodium: 5,
    sugar: 29,
  },
  {
    name: 'Watermelon Juice (8 oz)',
    calories: 71,
    carbs: 18,
    fat: 0,
    protein: 1,
    sodium: 4,
    sugar: 17,
  },
  {
    name: 'Iced Chai Latte (8 oz, sweetened)',
    calories: 150,
    carbs: 31,
    fat: 2,
    protein: 2,
    sodium: 60,
    sugar: 30,
  },
  {
    name: 'Mint Tea (8 oz)',
    calories: 0,
    carbs: 0,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
  },
  {
    name: 'Lavender Lemonade (8 oz)',
    calories: 100,
    carbs: 27,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 25,
  },
  {
    name: 'Arnold Palmer (8 oz)',
    calories: 55,
    carbs: 15,
    fat: 0,
    protein: 0,
    sodium: 0,
    sugar: 15,
  },
  {
    name: 'Salmon (100g)',
    calories: 206,
    carbs: 0,
    fat: 13.4,
    protein: 22,
    sodium: 50,
    sugar: 0,
  },
  {
    name: 'Tuna (100g)',
    calories: 144,
    carbs: 0,
    fat: 1,
    protein: 30,
    sodium: 38,
    sugar: 0,
  },
  {
    name: 'Trout (100g)',
    calories: 119,
    carbs: 0,
    fat: 5.6,
    protein: 17,
    sodium: 44,
    sugar: 0,
  },
  {
    name: 'Bass (100g)',
    calories: 97,
    carbs: 0,
    fat: 2.6,
    protein: 18.6,
    sodium: 57,
    sugar: 0,
  },
  {
    name: 'Catfish (100g)',
    calories: 105,
    carbs: 0,
    fat: 6,
    protein: 20,
    sodium: 50,
    sugar: 0,
  },
  {
    name: 'Cod (100g)',
    calories: 82,
    carbs: 0,
    fat: 0.7,
    protein: 18,
    sodium: 75,
    sugar: 0,
  },
  {
    name: 'Sardine (100g)',
    calories: 208,
    carbs: 0,
    fat: 11.5,
    protein: 24,
    sodium: 500,
    sugar: 0,
  },
  {
    name: 'Mackerel (100g)',
    calories: 305,
    carbs: 0,
    fat: 25,
    protein: 18,
    sodium: 90,
    sugar: 0,
  },
  {
    name: 'Haddock (100g)',
    calories: 74,
    carbs: 0,
    fat: 0.7,
    protein: 17,
    sodium: 94,
    sugar: 0,
  },
  {
    name: 'Halibut',
    calories: 90,
    carbs: 0,
    fat: 2.3,
    protein: 18,
    sodium: 77,
    sugar: 0,
  },
  {
    name: 'Perch (100g)',
    calories: 96,
    carbs: 0,
    fat: 2,
    protein: 20,
    sodium: 70,
    sugar: 0,
  },
  {
    name: 'Flounder (100g)',
    calories: 86,
    carbs: 0,
    fat: 1.5,
    protein: 17,
    sodium: 68,
    sugar: 0,
  },
  {
    name: 'Grouper (100g)',
    calories: 92,
    carbs: 0,
    fat: 2,
    protein: 19,
    sodium: 59,
    sugar: 0,
  },
  {
    name: 'Snapper (100g)',
    calories: 113,
    carbs: 0,
    fat: 1.3,
    protein: 24,
    sodium: 61,
    sugar: 0,
  },
]

// You can continue to add more food items as needed.
